steps:
  - block: "Build dev APK?"
    # Always run if this is a Kolibri release
    if: build.env("LE_KOLIBRI_RELEASE") != "true"

  - label: "Build dev APK"
    command: ".buildkite/build.sh"
    env: KOLIBRI_ANDROID_BUILD_MODE=dev

  - block: "Build release APK?"
    # Always run if this is a Kolibri release
    if: build.env("LE_KOLIBRI_RELEASE") == "true"

  - label: "Build Release APK (32bit) :tada:"
    command: ".buildkite/build.sh"
    env: KOLIBRI_ANDROID_BUILD_MODE=release

  - label: "Build Release APK (64bit) :tada:"
    command: ".buildkite/build.sh"
    env: KOLIBRI_ANDROID_BUILD_MODE=release ARCH=64bit