steps:
  - block: "Build APK?"
    # Block if this is triggered from Kolibri pipeline and is not a release
    if: build.source == "trigger_job"

  - label: "Build Dev Android APK (32bit) :tada:"
    command: ".buildkite/build.sh"
    env:
      KOLIBRI_ANDROID_BUILD_MODE: "dev"

  - label: "Build Dev Android APK (64bit) :tada:"
    command: ".buildkite/build.sh"
    env:
      KOLIBRI_ANDROID_BUILD_MODE: "dev"
      ARCH: "64bit"
