steps:
  - block: "Build :android:?"
  - if: build.source == "trigger_job"
  
  # TODO make this independantly triggerable
  # Only block when build is triggered by another build
  - label: "Dev Build APK"
    command: ".buildkite/build.sh"
